#!/usr/bin/sh

sxhkd &
~/.config/polybar/launch.sh &
picom &
nitrogen --restore &
xcalib -s :0 /usr/share/color/icc/N156HCE_GN1.icm &

bspc monitor -d 1 2 3 4 5 6 7 8

# Window Padding
bspc config border_width         2
bspc config window_gap          12
bspc config top_padding 	24 

bspc config top_monocle_padding    12
bspc config right_monocle_padding  12
bspc config left_monocle_padding   12
bspc config bottom_monocle_padding 12

# Window Visuals
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true
bspc config auto_alternate true
bspc config auto_cancel true
bspc config border_width 0
bspc config normal_border_color "#5e81ac"
bspc config active_border_color "#d8dee9"
bspc config focused_border_color "#d8dee9"
bspc config presel_border_color "#d8dee9"
bspc config urgent_border_color "#bf616a"
bspc config focused_locked_border_color "#d8dee9"
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1

# Window Rules
bspc rule -a Firefox desktop='^2'
bspc rule -a kitty desktop='^1'
